# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from userAdmin.models import Patient,Doctor, Administrator

class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20170808_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='primary_physician',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAdmin.Patient'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
