# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deviceToken',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
