# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0002_patient_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formType', models.CharField(max_length=50)),
                ('submissionFrequency', models.CharField(max_length=20)),
                ('lastReminder', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='submitsBackPain',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='submitsLBPCharacterise',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='submitsPPD',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='submitsPainForm',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreminders',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_patient', to='userAdmin.Patient'),
        ),
    ]
